name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: guilhermek9/streaming_app
  TAG: ${{ github.sha }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Diagnostico de Secrets do Docker
        run: | # <--- AQUI DEVE ESTAR PERFEITAMENTE ALINHADO
          echo "Verificando DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
          echo "Verificando DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}"
          echo "Verificando se DOCKER_USERNAME tem um valor: ${{ secrets.DOCKER_USERNAME != '' }}"

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }}

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: SSH into OCI Server and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USERNAME }}
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
            echo "Deploying new version..."
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
            docker pull ${{ env.DOCKER_IMAGE_NAME }}:${{ env.TAG }}
            docker-compose -f /caminho/para/seu/docker-compose.yml up -d --force-recreate
            echo "Deployment complete!"